# This is a basic workflow to help you get started with Actions

name: GTests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

# temp
      - name: Start process
        run: echo Starting Unit test
      - name: Create Tmp folder
        run: mkdir Tmp
      - name: Get premake
        run: wget -O Tmp/premake.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta1/premake-5.0.0-beta1-linux.tar.gz 
      - name: Unpack
        run: tar -xf Tmp/premake.tar.gz -C Tmp/
      - name: Get tmp files
        run: ls Tmp/
      - name: Update premake permission
        run: chmod +x Tmp/premake5
      - name: Generate solution
        run: ./Tmp/premake5 --file=./Scripts/MQTT.lua gmake2
      - name: Make files
        run: make
      - name: Run unit test
        run: ./bin/Debug-linux/UnitTest/UnitTest
        
